In [1]:
import pandas as pd
import numpy as np
import sys 
import json
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
import itertools
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

from joblib import Parallel, delayed, dump, load
# sys.path.insert(0, '../DevCode')


pd.set_option('display.expand_frame_repr', False)
pd.options.display.max_rows = 500
sys.path.append('../src')
import pickle
from src.DataManager import BetterTokenizer

In [ ]:
scaler = MinMaxScaler(feature_range=(0,1))

In [3]:
import torch
import torch.nn as nn

In [4]:
token_items = json.load(open('code/data/token1.json'))

In [9]:
token_items

{'token_to_id': {'<PAD>': 0,
  'br': 1,
  '-': 2,
  'icloud': 3,
  '.': 4,
  'com': 5,
  'mp3raid': 6,
  '/': 7,
  'music': 8,
  'krizz_kaliko': 9,
  'html': 10,
  'bopsecrets': 11,
  'org': 12,
  'rexroth': 13,
  'cr': 14,
  '1': 15,
  'htm': 16,
  'http': 17,
  ':': 18,
  'www': 19,
  'garage': 20,
  'pirenne': 21,
  'be': 22,
  'index': 23,
  'php': 24,
  '?': 25,
  'option': 26,
  '=': 27,
  'com_content': 28,
  '&': 29,
  'view': 30,
  'article': 31,
  'id': 32,
  '70': 33,
  'vsig70_0': 34,
  '15': 35,
  'adventure': 36,
  'nicaragua': 37,
  'net': 38,
  'com_mailto': 39,
  'tmpl': 40,
  'component': 41,
  'link': 42,
  'aHR0cDovL2FkdmVudHVyZS1uaWNhcmFndWEubmV0L2luZGV4LnBocD9vcHRpb249Y29tX2NvbnRlbnQmdmlldz1hcnRpY2xlJmlkPTQ3OmFib3V0JmNhdGlkPTM2OmRlbW8tYXJ0aWNsZXMmSXRlbWlkPTU0': 43,
  'buzzfil': 44,
  'm': 45,
  'show': 46,
  'art': 47,
  'ils': 48,
  'etaient': 49,
  'loin': 50,
  'de': 51,
  's': 52,
  'imaginer': 53,
  'que': 54,
  'le': 55,
  'hibou': 56,
  'allait': 57,
  'fai

In [4]:
# model = load('./code/data/gb_model.joblib')

In [4]:
bt = BetterTokenizer(starting_tokenizer=token_items)

NameError: name 'token_items' is not defined

In [2]:
from src.Simulator import Simulator, TestingSampler



In [3]:
sm = Simulator()

In [4]:
sm.run()

Model is predicting the URL Beautifulkhachcomcom4cQj2nQLYek-htmlcomcaltech-huilshonorsloinfinancialaidtipsquickfactscelebidloinszabadmunkaeroquickfactsqfdloin186981khachprestigeclockrepairquickfactshcschoolsloin86khach70876929quickfactsrazorianflyloinsouthwest to be 
 phishing
The LSTM predicted benign
The Actual URL is defacement
---------------------------------------------------------------------------
Model is predicting the URL pgh-.comdeluxecomgrassrootsenterprisescomshortscommythscomcaltech-id to be 
 benign
The LSTM predicted phishing
The Actual URL is benign
---------------------------------------------------------------------------
Model is predicting the URL picosecondindexreyes-.comT4VCH8S37AQES3JP7-huilsqfdloinnm0152460 to be 
 phishing
The LSTM predicted phishing
The Actual URL is benign
---------------------------------------------------------------------------
Model is predicting the URL government-.comsectioncomvideo178712indexmallindexmilkandcookiescomrfc2942 to be 
 

In [13]:
sample = sm.sampler.get_sample()

In [8]:
sample

array([1.68220e+04, 4.00000e+00, 1.48127e+05, 4.00000e+00, 1.34000e+02,
       4.00000e+00, 1.25000e+02, 7.00000e+00, 5.83103e+05, 7.00000e+00,
       2.30000e+01, 4.00000e+00, 1.60000e+01, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00])

In [13]:
model.predict(sample.reshape(1,-1))[0]

0

In [7]:
token_data = pd.read_pickle('./notebooks/url.pkl')

In [8]:
token_data

0                                     [1, 2, 3, 4, 5, 4, 1]
1                              [6, 4, 5, 7, 8, 7, 9, 4, 10]
2                   [11, 4, 12, 7, 13, 7, 14, 7, 15, 4, 16]
3         [17, 18, 7, 7, 19, 4, 20, 2, 21, 4, 22, 7, 23,...
4         [17, 18, 7, 7, 36, 2, 37, 4, 38, 7, 23, 4, 24,...
                                ...                        
651186    [62048, 4, 3247, 4, 5, 7, 3248, 7, 3758, 7, 62...
651187    [2686, 4, 45660, 4, 5, 7, 23449, 2, 4843, 7, 1...
651188    [19, 4, 8613, 4, 5, 7, 62048, 7, 5920, 7, 4298...
651189    [187, 4, 188, 4, 12, 7, 189, 7, 627327, 327, 3...
651190        [19, 4, 15712, 4, 5, 7, 612669, 7, 627328, 7]
Name: url, Length: 651191, dtype: object

In [9]:
sm.tokenizer.decode(token_data[0])

'br-icloud.com.br'

In [12]:
sm.tokenizer.decode(token_data[0])

'br-icloud.com.br'

In [13]:
sm.tokenizer.decode_padded(sample)

'tools.ietf.org/html/rfc2488'

In [8]:
lstm_sample = sm.sampler.sample[0].reshape(-1, 47, 1)

In [12]:
sm.sampler.sample[0]

array([1.90000e+01, 4.00000e+00, 5.85477e+05, 4.00000e+00, 5.00000e+00,
       7.00000e+00, 3.35540e+04, 7.00000e+00, 5.35000e+02, 7.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00])

In [19]:
sm.sampler.testing_data.shape

(94419, 47)

In [23]:
sm.sampler.testing_data[sm.sampler.sample_int]

array([5.3214e+05, 4.0000e+00, 2.2000e+01, 7.0000e+00, 1.4425e+04,
       7.0000e+00, 4.3089e+04, 2.9000e+01, 4.3090e+04, 4.0000e+00,
       1.6000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00])

In [22]:
sm.sampler.lstm_y_val[sm.sampler.sample_int]

array([[8.48495430e-01],
       [6.40175152e-06],
       [3.50703240e-05],
       [1.11801798e-05],
       [2.30216172e-02],
       [1.11928366e-05],
       [6.86877607e-02],
       [4.62486006e-05],
       [6.86881504e-02],
       [6.37908680e-06],
       [2.55050803e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],


In [24]:
lstm_data = sm.sampler.testing_data.copy()
lstm_data = scaler.fit_transform(lstm_data)

In [35]:
lstm_data = sm.sampler.testing_data.copy()

In [41]:
lstm_data.shape

(94419, 47)

In [25]:
lstm_data[0]

array([2.55119938e-05, 2.88078818e-05, 1.11587394e-05, 1.11801798e-05,
       4.86127181e-03, 6.39590662e-06, 2.22694427e-03, 6.37911732e-06,
       4.53032544e-03, 6.37908680e-06, 1.08587879e-02, 1.11589173e-05,
       8.18571932e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [36]:
features = scaler.fit_transform(lstm_data)

In [37]:
features = lstm_data.reshape(-1, 47, 1)

In [38]:
features

array([[[1.7000e+01],
        [1.8000e+01],
        [7.0000e+00],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.7000e+01],
        [1.8000e+01],
        [7.0000e+00],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.7000e+01],
        [1.8000e+01],
        [7.0000e+00],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       ...,

       [[1.9000e+01],
        [4.0000e+00],
        [8.6130e+03],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.8700e+02],
        [4.0000e+00],
        [1.8800e+02],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.9000e+01],
        [4.0000e+00],
        [1.5712e+04],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]]])

In [39]:
test_int = 1200

In [29]:
sm.sampler.sample[0]

array([5.3214e+05, 4.0000e+00, 2.2000e+01, 7.0000e+00, 1.4425e+04,
       7.0000e+00, 4.3089e+04, 2.9000e+01, 4.3090e+04, 4.0000e+00,
       1.6000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00])

In [40]:
sm.sampler.testing_data[test_int]

array([1.70000e+01, 1.80000e+01, 7.00000e+00, 7.00000e+00, 3.49800e+03,
       4.00000e+00, 2.63950e+04, 4.00000e+00, 1.39700e+03, 4.00000e+00,
       3.68990e+04, 7.00000e+00, 5.13596e+05, 7.00000e+00, 5.13516e+05,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00])

In [41]:
features[test_int]

array([[1.70000e+01],
       [1.80000e+01],
       [7.00000e+00],
       [7.00000e+00],
       [3.49800e+03],
       [4.00000e+00],
       [2.63950e+04],
       [4.00000e+00],
       [1.39700e+03],
       [4.00000e+00],
       [3.68990e+04],
       [7.00000e+00],
       [5.13596e+05],
       [7.00000e+00],
       [5.13516e+05],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.

In [19]:
features.shape

(94419, 47, 1)

In [13]:
lstm_sample

array([[[1.90000e+01],
        [4.00000e+00],
        [5.85477e+05],
        [4.00000e+00],
        [5.00000e+00],
        [7.00000e+00],
        [3.35540e+04],
        [7.00000e+00],
        [5.35000e+02],
        [7.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.00000e+00],
        [0.

In [13]:
sm.sampler.get_sample()

array([1.90000e+01, 4.00000e+00, 6.14227e+05, 4.00000e+00, 5.00000e+00,
       7.00000e+00, 6.19357e+05, 7.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00])

In [14]:
sm.sampler.sample_int

86413

In [16]:
sm.sampler.lstm_y_val[]

array([[[2.55119938e-05],
        [2.88078818e-05],
        [1.11587394e-05],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[2.55119938e-05],
        [2.88078818e-05],
        [1.11587394e-05],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[2.55119938e-05],
        [2.88078818e-05],
        [1.11587394e-05],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       ...,

       [[2.87009931e-05],
        [6.40175152e-06],
        [1.37300318e-02],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[2.96576928e-04],
        [6.40175152e-06],
        [2.99691859e-04],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[2.87009931e-05],
        [6.40175152e-06],
        [2.50465877e-02],
        ...,
        [0.00000000e+00],
        [0.0000

In [14]:
sample = sm.sampler.get_lstm_sample()

In [17]:
sm.sampler.testing_data[sm.sampler.sample_int]

array([1.90000e+01, 4.00000e+00, 5.92844e+05, 4.00000e+00, 5.00000e+00,
       7.00000e+00, 1.87965e+05, 7.00000e+00, 5.92845e+05, 7.00000e+00,
       1.37700e+03, 7.00000e+00, 5.35000e+02, 7.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00])

In [18]:
sm.sampler.unscaled_lstm_features

array([[[1.7000e+01],
        [1.8000e+01],
        [7.0000e+00],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.7000e+01],
        [1.8000e+01],
        [7.0000e+00],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.7000e+01],
        [1.8000e+01],
        [7.0000e+00],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       ...,

       [[1.9000e+01],
        [4.0000e+00],
        [8.6130e+03],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.8700e+02],
        [4.0000e+00],
        [1.8800e+02],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]],

       [[1.9000e+01],
        [4.0000e+00],
        [1.5712e+04],
        ...,
        [0.0000e+00],
        [0.0000e+00],
        [0.0000e+00]]])

In [16]:
sm.sampler.unscaled_lstm_features[sm.sampler.sample_int]

array([[1.90000e+01],
       [4.00000e+00],
       [5.92844e+05],
       [4.00000e+00],
       [5.00000e+00],
       [7.00000e+00],
       [1.87965e+05],
       [7.00000e+00],
       [5.92845e+05],
       [7.00000e+00],
       [1.37700e+03],
       [7.00000e+00],
       [5.35000e+02],
       [7.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.00000e+00],
       [0.

In [15]:
sample

array([[2.87009931e-05],
       [6.40175152e-06],
       [9.45055961e-01],
       [6.38867416e-06],
       [7.97976332e-06],
       [1.11928366e-05],
       [2.99633200e-01],
       [1.11634553e-05],
       [9.45031945e-01],
       [1.11634019e-05],
       [2.19503097e-03],
       [1.11589173e-05],
       [8.52830201e-04],
       [1.11725245e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],


In [37]:
sm.sampler.scaler.inverse_transform(sample)

ValueError: non-broadcastable output operand with shape (47,1) doesn't match the broadcast shape (47,47)

In [36]:
sample

array([[2.87009931e-05],
       [6.40175152e-06],
       [9.79142722e-01],
       [6.38867416e-06],
       [7.97976332e-06],
       [1.11928366e-05],
       [9.87311041e-01],
       [1.11634553e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],


In [28]:
st = torch.tensor(sample, dtype=torch.float32, device=device).unsqueeze(0)

In [33]:
output = model(st)


In [35]:
output.argmax().item()

0

In [15]:
sm.sampler.get_lstm_sample()

array([[2.87009931e-05],
       [6.40175152e-06],
       [9.79142722e-01],
       [6.38867416e-06],
       [7.97976332e-06],
       [1.11928366e-05],
       [9.87311041e-01],
       [1.11634553e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
